
set(STM_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../STM_sdk)
file(GLOB_RECURSE STM32CUBEMX_SOURCES ${STM_DIR}/Core/*.c ${STM_DIR}/Drivers/STM32F4xx_HAL_Driver/*.c)
set(STARTUP_SCRIPT ${STM_DIR}/startup_stm32f446xx.s)

target_sources(${LF_MAIN_TARGET} PRIVATE ${STM32CUBEMX_SOURCES} )

add_custom_command(TARGET ${LF_MAIN_TARGET} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${LF_MAIN_TARGET}>)
add_custom_command(TARGET ${LF_MAIN_TARGET} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex $<TARGET_FILE:${LF_MAIN_TARGET}>
    ${LF_MAIN_TARGET}.hex
    COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${LF_MAIN_TARGET}>
    ${LF_MAIN_TARGET}.bin)